services:
  linux-home-page:
    build:
      context: .
      network: host
    image: linux-home-page:latest
    container_name: linux-home-page
    ports:
      - "8081:80"
      - "11443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.crt:/etc/nginx/ssl/nginx.crt:ro
      - ./nginx.key:/etc/nginx/ssl/nginx.key:ro
    restart: always

networks:
  default:
    name: global-link
    external: true
